/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import communitylookuptool.User;
import javax.swing.JTextField;
import mvc.cntl.LoginCntl;

/**
 *
 * @author bryce
 */
public class LoginUI extends javax.swing.JFrame {

	private LoginCntl loginCntl;

	/**
	 * Creates new form LoginUI
	 */
	public LoginUI(LoginCntl loginCntl) {
		this.loginCntl = loginCntl;
		initComponents();
		showLoginUI();
	}

	public String getTextFieldPassword() {
		return textFieldPassword.getText();
	}

	public String getTextFieldUsername() {
		return textFieldUsername.getText();
	}

	public void setTextFieldPassword(JTextField textFieldPassword) {
		this.textFieldPassword = textFieldPassword;
	}

	public void setTextFieldUsername(JTextField textFieldUsername) {
		this.textFieldUsername = textFieldUsername;
	}

	public void showLoginUI() {
		txtTitle.setText("Login");
		txtTitle.setVisible(true);
		txtUsername.setVisible(true);
		txtPassword.setVisible(true);
		textFieldUsername.setVisible(true);
		textFieldPassword.setVisible(true);
		btnLogin.setVisible(true);
		btnQuit.setVisible(true);
		btnCreateAccount.setVisible(true);
		btnBack.setVisible(false);
		btnCreate.setVisible(false);
	}

	public void showCreateAccountUI() {
		txtTitle.setText("Create Account");
		txtTitle.setVisible(true);
		txtUsername.setVisible(true);
		txtPassword.setVisible(true);
		textFieldUsername.setVisible(true);
		textFieldPassword.setVisible(true);
		btnLogin.setVisible(false);
		btnQuit.setVisible(false);
		btnCreateAccount.setVisible(false);
		btnBack.setVisible(true);
		btnCreate.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                btnQuit = new javax.swing.JButton();
                textFieldUsername = new javax.swing.JTextField();
                textFieldPassword = new javax.swing.JTextField();
                txtUsername = new javax.swing.JLabel();
                txtPassword = new javax.swing.JLabel();
                txtTitle = new javax.swing.JLabel();
                btnLogin = new javax.swing.JButton();
                btnCreateAccount = new javax.swing.JButton();
                btnBack = new javax.swing.JButton();
                btnCreate = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnQuit.setText("Quit");
                btnQuit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnQuitActionPerformed(evt);
                        }
                });

                txtUsername.setText("Username:");

                txtPassword.setText("Password");

                txtTitle.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
                txtTitle.setText("Login");

                btnLogin.setText("Login");
                btnLogin.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLoginActionPerformed(evt);
                        }
                });

                btnCreateAccount.setText("Create Account");
                btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCreateAccountActionPerformed(evt);
                        }
                });

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                btnCreate.setText("Create");
                btnCreate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCreateActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(btnBack)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLogin))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txtPassword, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtTitle)
                                        .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnCreateAccount)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnQuit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnCreate)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(txtTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsername))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPassword)
                                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnQuit)
                                        .addComponent(btnLogin)
                                        .addComponent(btnCreateAccount)
                                        .addComponent(btnBack)
                                        .addComponent(btnCreate))
                                .addGap(26, 26, 26))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 25, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
	    User user = new User(textFieldUsername.getText(), textFieldPassword.getText());
	    loginCntl.requestAuthentication(user);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
	    System.exit(0);
    }//GEN-LAST:event_btnQuitActionPerformed

        private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
		showCreateAccountUI();
        }//GEN-LAST:event_btnCreateAccountActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                showLoginUI();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
		User user = new User(textFieldUsername.getText(), textFieldPassword.getText());
		loginCntl.addUser(user);
        }//GEN-LAST:event_btnCreateActionPerformed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnBack;
        private javax.swing.JButton btnCreate;
        private javax.swing.JButton btnCreateAccount;
        public javax.swing.JButton btnLogin;
        public javax.swing.JButton btnQuit;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JTextField textFieldPassword;
        private javax.swing.JTextField textFieldUsername;
        private javax.swing.JLabel txtPassword;
        private javax.swing.JLabel txtTitle;
        private javax.swing.JLabel txtUsername;
        // End of variables declaration//GEN-END:variables
}
