/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import javax.swing.SwingConstants;
import mvc.cntl.NavigationCntl;

/**
 *
 * @author bzc5373
 */
public class NavigationView extends javax.swing.JFrame {
    private NavigationCntl navCntl;
    /**
     * Creates new form NavigationCntl
     */
    public NavigationView(NavigationCntl navCntl) {
        this.navCntl = navCntl; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnResults = new javax.swing.JButton();
                btnLogout = new javax.swing.JButton();
                bntQuit = new javax.swing.JButton();
                btnTableResults = new javax.swing.JButton();
                labelTitle = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                btnResults.setText("Results");
                btnResults.setHorizontalAlignment(SwingConstants.CENTER);
                btnResults.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnResultsActionPerformed(evt);
                        }
                });

                btnLogout.setText("Logout");
                btnLogout.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnLogoutActionPerformed(evt);
                        }
                });

                bntQuit.setText("Quit");
                bntQuit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                bntQuitActionPerformed(evt);
                        }
                });

                btnTableResults.setText("Table Results");
                btnTableResults.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnTableResultsActionPerformed(evt);
                        }
                });

                labelTitle.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
                labelTitle.setHorizontalAlignment(SwingConstants.CENTER);
                labelTitle.setText("Navigation");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnLogout)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntQuit)
                                .addGap(51, 51, 51))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(156, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTitle)
                                        .addComponent(btnTableResults)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(btnResults)))
                                .addGap(143, 143, 143))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle)
                                .addGap(54, 54, 54)
                                .addComponent(btnResults)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addComponent(btnTableResults)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnLogout)
                                        .addComponent(bntQuit))
                                .addGap(38, 38, 38))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultsActionPerformed
        navCntl.moveToResult();
    }//GEN-LAST:event_btnResultsActionPerformed

    private void bntQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntQuitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bntQuitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        navCntl.moveToLogin();
    }//GEN-LAST:event_btnLogoutActionPerformed

        private void btnTableResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableResultsActionPerformed
                navCntl.moveToResultTable();
        }//GEN-LAST:event_btnTableResultsActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton bntQuit;
        private javax.swing.JButton btnLogout;
        private javax.swing.JButton btnResults;
        private javax.swing.JButton btnTableResults;
        private javax.swing.JLabel labelTitle;
        // End of variables declaration//GEN-END:variables
}
