/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mvc.view;

import communitylookuptool.Person;
import java.util.ArrayList;
import mvc.cntl.ResultCntl;

/**
 *
 * @author bzc5373
 */
public class ResultView extends javax.swing.JFrame {
    private ResultCntl resultCntl;
//    private ArrayList<Person> listOfPeople;
//    private int currentPerson = 0;
//    private Person person;
//    private int selectedRow;
//    public int getCurrentPerson() {
//        return currentPerson;
//    }

//    public void setCurrentPerson(int currentPerson) {
//        this.currentPerson = currentPerson;
//    }
    
    /**
     * Creates new form ResultView
     */
    public ResultView(ResultCntl resultCntl) {
        this.resultCntl = resultCntl; 
        initComponents();
    }

    public void parsePerson(Person person) {
        txtFirstName.setText(person.getFirstName());
        txtLastName.setText(person.getLastName());
        txtCampus.setText(person.getCampus());
    }
    
    public String getFirstName() {
        return txtFirstName.getText();
    }   
    
    public String getLastName() {
        return txtLastName.getText();
    }
    
    public String getCampus() {
        return txtCampus.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                labelTitle = new javax.swing.JLabel();
                btnNext = new javax.swing.JButton();
                btnAdd = new javax.swing.JButton();
                btnUpdate = new javax.swing.JButton();
                btnQuit = new javax.swing.JButton();
                btnDelete = new javax.swing.JButton();
                btnPrev = new javax.swing.JButton();
                labelFirstName = new javax.swing.JLabel();
                txtFirstName = new javax.swing.JTextField();
                labelLastName = new javax.swing.JLabel();
                txtLastName = new javax.swing.JTextField();
                labelCampus = new javax.swing.JLabel();
                txtCampus = new javax.swing.JTextField();
                btnBack = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                labelTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
                labelTitle.setText("Results");

                btnNext.setText("Next");
                btnNext.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnNextActionPerformed(evt);
                        }
                });

                btnAdd.setText("Add");
                btnAdd.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnAddActionPerformed(evt);
                        }
                });

                btnUpdate.setText("Update");
                btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnUpdateActionPerformed(evt);
                        }
                });

                btnQuit.setText("Quit");
                btnQuit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnQuitActionPerformed(evt);
                        }
                });

                btnDelete.setText("Delete");
                btnDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnDeleteActionPerformed(evt);
                        }
                });

                btnPrev.setText("Prev");
                btnPrev.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnPrevActionPerformed(evt);
                        }
                });

                labelFirstName.setText("First Name:");

                labelLastName.setText("Last Name:");

                labelCampus.setText("Campus");

                btnBack.setText("Back");
                btnBack.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnBackActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(181, 181, 181)
                                                                .addComponent(labelTitle))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(148, 148, 148)
                                                                .addComponent(btnPrev)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(btnDelete))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(34, 34, 34)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(labelFirstName)
                                                                                                .addComponent(labelLastName)
                                                                                                .addComponent(labelCampus))
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(btnBack)
                                                                                                .addGap(17, 17, 17)))
                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                .addGap(38, 38, 38)
                                                                                                .addComponent(txtCampus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                        .addComponent(txtFirstName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                .addGap(11, 11, 11))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(49, 49, 49)
                                                .addComponent(btnNext)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAdd)
                                                .addGap(17, 17, 17)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnUpdate)
                                        .addComponent(btnQuit))
                                .addGap(41, 41, 41))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelTitle)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelFirstName)
                                        .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelLastName)
                                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCampus)
                                        .addComponent(txtCampus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnNext)
                                        .addComponent(btnAdd)
                                        .addComponent(btnUpdate))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnDelete)
                                        .addComponent(btnPrev)
                                        .addComponent(btnQuit)
                                        .addComponent(btnBack))
                                .addContainerGap(29, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed

	    if (resultCntl.getCurrentPerson() == 0) {
		    
                resultCntl.setCurrentPerson(resultCntl.getListOfPeople().size() -1);
            } else {
                resultCntl.setCurrentPerson(resultCntl.getCurrentPerson() - 1);
            }
	   parsePerson(resultCntl.getListOfPeople().get(resultCntl.getCurrentPerson()));
    }//GEN-LAST:event_btnPrevActionPerformed

        private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
                resultCntl.moveToNav();
        }//GEN-LAST:event_btnBackActionPerformed

        private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
                Person person = new Person( txtFirstName.getText(), txtLastName.getText(), txtCampus.getText());
//		resultCntl.getListOfPeople().
		resultCntl.getPersonList().addPerson(person);
		parsePerson(resultCntl.getListOfPeople().get(resultCntl.getCurrentPerson()));
        }//GEN-LAST:event_btnAddActionPerformed

        private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
            if (resultCntl.getCurrentPerson() ==  resultCntl.getListOfPeople().size() - 1) {
	    
//		    listOfPeople.size() - 1) {
		resultCntl.setCurrentPerson(0);
//                currentPerson = 0;
            } else {
//                currentPerson++;
		resultCntl.setCurrentPerson(resultCntl.getCurrentPerson() + 1);
            }
	    parsePerson(resultCntl.getListOfPeople().get(resultCntl.getCurrentPerson()));
        }//GEN-LAST:event_btnNextActionPerformed

        private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
//              resultCntl.getListOfPeople().remove(resultCntl.getCurrentPerson());
		resultCntl.getPersonList().removePerson(resultCntl.getListOfPeople().get(resultCntl.getCurrentPerson()));
        }//GEN-LAST:event_btnDeleteActionPerformed

        private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                Person person = resultCntl.getListOfPeople().get(resultCntl.getCurrentPerson());
		if (!(person.getFirstName().equals(txtFirstName.getText()))) {
                person.setFirstName(txtFirstName.getText());
            }            
            
            if (!(person.getLastName().equals(txtLastName.getText()))) {
                person.setLastName(txtLastName.getText());
            }
            
            if (!(person.getCampus().equals(txtCampus.getText()))) {
                person.setCampus(txtCampus.getText());
            }
	    
//	    resultCntl.getPersonList().updatePerson(resultCntl.getCurrentPerson(), person);
		resultCntl.getPersonList().updatePerson(resultCntl.getCurrentPerson(), person);
        }//GEN-LAST:event_btnUpdateActionPerformed

        private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
                System.exit(0);
        }//GEN-LAST:event_btnQuitActionPerformed

        // Variables declaration - do not modify//GEN-BEGIN:variables
        public javax.swing.JButton btnAdd;
        private javax.swing.JButton btnBack;
        public javax.swing.JButton btnDelete;
        public javax.swing.JButton btnNext;
        public javax.swing.JButton btnPrev;
        public javax.swing.JButton btnQuit;
        public javax.swing.JButton btnUpdate;
        private javax.swing.JLabel labelCampus;
        private javax.swing.JLabel labelFirstName;
        private javax.swing.JLabel labelLastName;
        private javax.swing.JLabel labelTitle;
        private javax.swing.JTextField txtCampus;
        private javax.swing.JTextField txtFirstName;
        private javax.swing.JTextField txtLastName;
        // End of variables declaration//GEN-END:variables
}
